# Конфигурация данных
data:
  dataset_path: "anthonytherrien/dog-vs-cat"  # Путь к датасету в Kaggle Hub
  #local_dir: "data"                         # Локальная директория для данных
  batch_size: 32                              # Размер батча
  train_ratio: 0.8                            # Доля тренировочных данных
  
# Параметры аугментации
augmentation:
  resize: [224, 224]                         # Размер изображения
  random_horizontal_flip: True               # Горизонтальное отражение
  random_rotation: 30                        # Угол поворота (градусы)
  color_jitter:                              # Параметры цветовых искажений
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.2
  random_affine_translate: [0.1, 0.1]        # Сдвиг для аффинных преобразований
  random_perspective:                        # Параметры перспективы
    distortion_scale: 0.5
    p: 0.5
    #interpolation: 3
  random_crop: 200                           # Размер случайной обрезки
  normalize:                                 # Параметры нормализации
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    
# Конфигурации модели
model:
  base:
    name: "resnet18" 
    pretrained: True
    num_classes: 2
    lr: 0.0001
    weight_decay: 0.0  # Без регуляризации
  
  l2_reg:
    name: "resnet18"
    pretrained: True
    num_classes: 2
    lr: 0.0001
    weight_decay: 0.0001  # С L2 регуляризацией
  
# Параметры обучения
training:
  num_epochs: 10                             # Количество эпох

# Настройки визуализации
visualization:
  colors:                                    # Цвета графиков
    train: "#1E90FF"
    test: "#FF4500"                             
  base_dir: "plots"                          # Директория для сохранения
  subdirs:
    without_reg: "without_regularization"
    l2_reg: "with_l2_regularization"
  filenames:                                 # Имена файлов
    metrics: "metrics_plot.png"
    confusion_matrix: "confusion_matrix.png"
